name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and run Go program
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}	# æœåŠ¡å™¨åœ°å€
          username: ${{ secrets.USRNAME }} # ç™»é™†ç”¨æˆ·å
          key: ${{ secrets.KEY }} # æœåŠ¡å™¨ç§é’¥
          port: 22
          script: |
            cd /usr/local/blog
            git checkout . && git pull &&
            if [ $? -ne 0 ]; then
              echo "æ‹‰å–å¤±è´¥ï¼Œè„šæœ¬ç»ˆæ­¢"
              exit 1
            fi &&
            docker stop myblog && docker rm myblog && docker rmi myapp:v1 &&
            docker build -t myapp:v1 .
            docker run -d -p 8080:80 --name myblog myapp:v1
            echo "è„šæœ¬æ‰§è¡Œå®Œæˆ"